// Code generated by goctl. DO NOT EDIT.
// Source: luna.proto

package server

import (
	"context"

	"su-wcbot/luna/internal/logic"
	"su-wcbot/luna/internal/svc"
	"su-wcbot/luna/wcbot"
)

type WcbotServer struct {
	svcCtx *svc.ServiceContext
	wcbot.UnimplementedWcbotServer
}

func NewWcbotServer(svcCtx *svc.ServiceContext) *WcbotServer {
	return &WcbotServer{
		svcCtx: svcCtx,
	}
}

func (s *WcbotServer) Ping(ctx context.Context, in *wcbot.Request) (*wcbot.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
